/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnsiblePlaybook: typeof import('./components/AnsiblePlaybook.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ArrayField: typeof import('./components/ArrayField.vue')['default']
    ChannelCandidateList: typeof import('./components/channelpedia/ChannelCandidateList.vue')['default']
    ChannelEditor: typeof import('./components/ChannelEditor.vue')['default']
    ChannelGroupDialogue: typeof import('./components/ChannelGroupDialogue.vue')['default']
    ChannelGroupInput: typeof import('./components/channelpedia/ChannelGroupInput.vue')['default']
    CpuUsageInfo: typeof import('./components/Dashboard/CpuUsageInfo.vue')['default']
    DiscUsageInfo: typeof import('./components/Dashboard/DiscUsageInfo.vue')['default']
    FanInfo: typeof import('./components/Dashboard/FanInfo.vue')['default']
    FileEditor: typeof import('./components/FileEditor.vue')['default']
    FileUpload: typeof import('./components/FileUpload.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HelpDialog: typeof import('./components/HelpDialog.vue')['default']
    LanguageOverlay: typeof import('./components/LanguageOverlay.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    LoginMask: typeof import('./components/LoginMask.vue')['default']
    LoginOverlay: typeof import('./components/LoginOverlay.vue')['default']
    LogoSelector: typeof import('./components/LogoSelector.vue')['default']
    MemoryInfo: typeof import('./components/Dashboard/MemoryInfo.vue')['default']
    MoveChannelInput: typeof import('./components/channelpedia/MoveChannelInput.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    NotificationQueueDisplay: typeof import('./components/NotificationQueueDisplay.vue')['default']
    PluginSettingsCard: typeof import('./components/PluginSettingsCard.vue')['default']
    RecordingsList: typeof import('./components/RecordingsList.vue')['default']
    RemoteControl: typeof import('./components/RemoteControl.vue')['default']
    RemoteIconButton: typeof import('./components/remote/RemoteIconButton.vue')['default']
    RemoteOverlay: typeof import('./components/RemoteOverlay.vue')['default']
    RemoteTextButton: typeof import('./components/remote/RemoteTextButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaField: typeof import('./components/SchemaField.vue')['default']
    SourceSelection: typeof import('./components/channelpedia/SourceSelection.vue')['default']
    StartArgumentDialog: typeof import('./components/StartArgumentDialog.vue')['default']
    SystemInfo: typeof import('./components/Dashboard/SystemInfo.vue')['default']
    TemperatureInfo: typeof import('./components/Dashboard/TemperatureInfo.vue')['default']
    TimerList: typeof import('./components/TimerList.vue')['default']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
  }
}
