/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChannelCandidateList: typeof import('./components/channelpedia/ChannelCandidateList.vue')['default']
    ChannelEditor: typeof import('./components/ChannelEditor.vue')['default']
    ChannelGroupDialogue: typeof import('./components/ChannelGroupDialogue.vue')['default']
    CpuUsageInfo: typeof import('./components/CpuUsageInfo.vue')['default']
    CreateChannelGroupInput: typeof import('./components/channelpedia/CreateChannelGroupInput.vue')['default']
    DiscUsageInfo: typeof import('./components/DiscUsageInfo.vue')['default']
    FanCard: typeof import('./components/FanCard.vue')['default']
    FileEditor: typeof import('./components/FileEditor.vue')['default']
    FileUpload: typeof import('./components/FileUpload.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginMask: typeof import('./components/LoginMask.vue')['default']
    LogoSelector: typeof import('./components/LogoSelector.vue')['default']
    MemoryInfo: typeof import('./components/MemoryInfo.vue')['default']
    MoveChannelInput: typeof import('./components/channelpedia/MoveChannelInput.vue')['default']
    RecordingsList: typeof import('./components/RecordingsList.vue')['default']
    RemoteControl: typeof import('./components/RemoteControl.vue')['default']
    RemoteIconButton: typeof import('./components/remote/RemoteIconButton.vue')['default']
    RemoteTextButton: typeof import('./components/remote/RemoteTextButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SourceSelection: typeof import('./components/channelpedia/SourceSelection.vue')['default']
    SystemInfo: typeof import('./components/SystemInfo.vue')['default']
    TemperatureCard: typeof import('./components/TemperatureCard.vue')['default']
    TimerList: typeof import('./components/TimerList.vue')['default']
  }
}
