/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChannelCandidateList: typeof import('./components/channelpedia/ChannelCandidateList.vue')['default']
    ChannelEditor: typeof import('./components/ChannelEditor.vue')['default']
    CpuUsageInfo: typeof import('./components/CpuUsageInfo.vue')['default']
    DiscUsageInfo: typeof import('./components/DiscUsageInfo.vue')['default']
    FanCard: typeof import('./components/FanCard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LogoSelector: typeof import('./components/LogoSelector.vue')['default']
    MemoryInfo: typeof import('./components/MemoryInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SourceSelection: typeof import('./components/channelpedia/SourceSelection.vue')['default']
    SystemInfo: typeof import('./components/SystemInfo.vue')['default']
    TemperatureCard: typeof import('./components/TemperatureCard.vue')['default']
  }
}
