/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/DashBoard': RouteRecordInfo<
      '/DashBoard',
      '/DashBoard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Installer/Assistant': RouteRecordInfo<
      '/Installer/Assistant',
      '/Installer/Assistant',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Installer/ConfigComponent': RouteRecordInfo<
      '/Installer/ConfigComponent',
      '/Installer/ConfigComponent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Installer/ConfigForm': RouteRecordInfo<
      '/Installer/ConfigForm',
      '/Installer/ConfigForm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/RemoteSettings': RouteRecordInfo<
      '/RemoteSettings',
      '/RemoteSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/System/AudioSettings': RouteRecordInfo<
      '/System/AudioSettings',
      '/System/AudioSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/System/ConfigFiles': RouteRecordInfo<
      '/System/ConfigFiles',
      '/System/ConfigFiles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/System/DisplaySettings': RouteRecordInfo<
      '/System/DisplaySettings',
      '/System/DisplaySettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/System/LogViewer': RouteRecordInfo<
      '/System/LogViewer',
      '/System/LogViewer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/System/Updates': RouteRecordInfo<
      '/System/Updates',
      '/System/Updates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/System/UploadFile': RouteRecordInfo<
      '/System/UploadFile',
      '/System/UploadFile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/SystemSettings': RouteRecordInfo<
      '/SystemSettings',
      '/SystemSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/VDR/ChannelpediaEditor': RouteRecordInfo<
      '/VDR/ChannelpediaEditor',
      '/VDR/ChannelpediaEditor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/VDR/ConfigFiles': RouteRecordInfo<
      '/VDR/ConfigFiles',
      '/VDR/ConfigFiles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/VDR/EPGViewer': RouteRecordInfo<
      '/VDR/EPGViewer',
      '/VDR/EPGViewer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/VDR/InfoDisplay': RouteRecordInfo<
      '/VDR/InfoDisplay',
      '/VDR/InfoDisplay',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/VDR/PluginSettings': RouteRecordInfo<
      '/VDR/PluginSettings',
      '/VDR/PluginSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/VDR/SetupEditor': RouteRecordInfo<
      '/VDR/SetupEditor',
      '/VDR/SetupEditor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/VDR/SetupEditor2': RouteRecordInfo<
      '/VDR/SetupEditor2',
      '/VDR/SetupEditor2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/VDR/VDRStartArguments': RouteRecordInfo<
      '/VDR/VDRStartArguments',
      '/VDR/VDRStartArguments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/DashBoard.vue': {
      routes:
        | '/DashBoard'
      views:
        | never
    }
    'src/pages/Installer/Assistant.vue': {
      routes:
        | '/Installer/Assistant'
      views:
        | never
    }
    'src/pages/Installer/ConfigComponent.vue': {
      routes:
        | '/Installer/ConfigComponent'
      views:
        | never
    }
    'src/pages/Installer/ConfigForm.vue': {
      routes:
        | '/Installer/ConfigForm'
      views:
        | never
    }
    'src/pages/RemoteSettings.vue': {
      routes:
        | '/RemoteSettings'
      views:
        | never
    }
    'src/pages/System/AudioSettings.vue': {
      routes:
        | '/System/AudioSettings'
      views:
        | never
    }
    'src/pages/System/ConfigFiles.vue': {
      routes:
        | '/System/ConfigFiles'
      views:
        | never
    }
    'src/pages/System/DisplaySettings.vue': {
      routes:
        | '/System/DisplaySettings'
      views:
        | never
    }
    'src/pages/System/LogViewer.vue': {
      routes:
        | '/System/LogViewer'
      views:
        | never
    }
    'src/pages/System/Updates.vue': {
      routes:
        | '/System/Updates'
      views:
        | never
    }
    'src/pages/System/UploadFile.vue': {
      routes:
        | '/System/UploadFile'
      views:
        | never
    }
    'src/pages/SystemSettings.vue': {
      routes:
        | '/SystemSettings'
      views:
        | never
    }
    'src/pages/VDR/ChannelpediaEditor.vue': {
      routes:
        | '/VDR/ChannelpediaEditor'
      views:
        | never
    }
    'src/pages/VDR/ConfigFiles.vue': {
      routes:
        | '/VDR/ConfigFiles'
      views:
        | never
    }
    'src/pages/VDR/EPGViewer.vue': {
      routes:
        | '/VDR/EPGViewer'
      views:
        | never
    }
    'src/pages/VDR/InfoDisplay.vue': {
      routes:
        | '/VDR/InfoDisplay'
      views:
        | never
    }
    'src/pages/VDR/PluginSettings.vue': {
      routes:
        | '/VDR/PluginSettings'
      views:
        | never
    }
    'src/pages/VDR/SetupEditor.vue': {
      routes:
        | '/VDR/SetupEditor'
      views:
        | never
    }
    'src/pages/VDR/SetupEditor2.vue': {
      routes:
        | '/VDR/SetupEditor2'
      views:
        | never
    }
    'src/pages/VDR/VDRStartArguments.vue': {
      routes:
        | '/VDR/VDRStartArguments'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
