/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/DashBoard': RouteRecordInfo<'/DashBoard', '/DashBoard', Record<never, never>, Record<never, never>>,
    '/Installer/Assistant': RouteRecordInfo<'/Installer/Assistant', '/Installer/Assistant', Record<never, never>, Record<never, never>>,
    '/Installer/ConfigComponent': RouteRecordInfo<'/Installer/ConfigComponent', '/Installer/ConfigComponent', Record<never, never>, Record<never, never>>,
    '/Installer/ConfigForm': RouteRecordInfo<'/Installer/ConfigForm', '/Installer/ConfigForm', Record<never, never>, Record<never, never>>,
    '/RemoteSettings': RouteRecordInfo<'/RemoteSettings', '/RemoteSettings', Record<never, never>, Record<never, never>>,
    '/System/AudioSettings': RouteRecordInfo<'/System/AudioSettings', '/System/AudioSettings', Record<never, never>, Record<never, never>>,
    '/System/DisplaySettings': RouteRecordInfo<'/System/DisplaySettings', '/System/DisplaySettings', Record<never, never>, Record<never, never>>,
    '/System/LogViewer': RouteRecordInfo<'/System/LogViewer', '/System/LogViewer', Record<never, never>, Record<never, never>>,
    '/System/Updates': RouteRecordInfo<'/System/Updates', '/System/Updates', Record<never, never>, Record<never, never>>,
    '/System/UploadFile': RouteRecordInfo<'/System/UploadFile', '/System/UploadFile', Record<never, never>, Record<never, never>>,
    '/SystemSettings': RouteRecordInfo<'/SystemSettings', '/SystemSettings', Record<never, never>, Record<never, never>>,
    '/VDR/ChannelpediaEditor': RouteRecordInfo<'/VDR/ChannelpediaEditor', '/VDR/ChannelpediaEditor', Record<never, never>, Record<never, never>>,
    '/VDR/ConfigFiles': RouteRecordInfo<'/VDR/ConfigFiles', '/VDR/ConfigFiles', Record<never, never>, Record<never, never>>,
    '/VDR/EPGViewer': RouteRecordInfo<'/VDR/EPGViewer', '/VDR/EPGViewer', Record<never, never>, Record<never, never>>,
    '/VDR/InfoDisplay': RouteRecordInfo<'/VDR/InfoDisplay', '/VDR/InfoDisplay', Record<never, never>, Record<never, never>>,
    '/VDR/PluginSettings': RouteRecordInfo<'/VDR/PluginSettings', '/VDR/PluginSettings', Record<never, never>, Record<never, never>>,
    '/VDR/SetupEditor': RouteRecordInfo<'/VDR/SetupEditor', '/VDR/SetupEditor', Record<never, never>, Record<never, never>>,
    '/VDR/SetupEditor2': RouteRecordInfo<'/VDR/SetupEditor2', '/VDR/SetupEditor2', Record<never, never>, Record<never, never>>,
    '/VDR/VDRStartArguments': RouteRecordInfo<'/VDR/VDRStartArguments', '/VDR/VDRStartArguments', Record<never, never>, Record<never, never>>,
  }
}
